library(cgmisc)
library(GenABEL)
library(visualTest)

test_that("pop allele counts work", {
  data.qc1 <- readRDS('data.qc1.rds')
  pop <- readRDS('pop.rds')
  pac <- pop.allele.counts(data = data.qc1[ ,data.qc1@gtdata@chromosome == 2], pops = pop, progress=F)
  expect_equal_to_reference(pac, 'pac.rds')
  
  # Test that the image generated by plot.pac is as it should be
  tmp <- tempfile(fileext = ".png")
  png(filename = tmp)
  plot.pac(data = data.qc1[ ,data.qc1@gtdata@chromosome == 2], allele.cnt = pac, plot.LD = T, legend.pos='topleft')
  dev.off()
  expect_true(isSimilar(file = tmp, fingerprint = "E9379273B462B1C1"))
})
