\documentclass[12pt,a4paper,oneside]{article}
\usepackage[usenames,dvipsnames]{xcolor}
\usepackage{graphicx}
\usepackage{amsmath}
\usepackage{booktabs}

<<setup, include=FALSE>>=
library(knitr)
opts_chunk$set(fig.width=9, fig.height=5, out.width="1.0\\textwidth",
   fig.keep="high",
   fig.show="hold",
   fig.align="center",
   dev='CairoPNG',
   fig.path='images/',
   highlight=TRUE,
   tidy=TRUE, size='footnotesize')
@

\begin{document}


<<include=FALSE>>=
library(knitr)
opts_chunk$set(
concordance=TRUE
)
@


\title{\color{TealBlue} cgmisc \\\ \normalsize Package containing various functions useful in computational genetics, especially in genome-wide association studies}
\author{\color{Orange}Marcin Kierczak}
\maketitle

\newpage

\section*{Introduction}
\subsection{Synopsis}
\noindent Package cgmisc contains miscellaneous functions, hopefully useful for extending genome-wide association study (GWAS) analyses.
\subsection{Getting help}
\noindent Like every other R function, the functions provided in this package are documented in the standard R-help (Rd) format and can be easily accessed by issuing \textbf{help}() or its shorter version, \textbf{?} function. For instance, if you want to get more information on how to use the clump.markers() function, type either help(clumpmarkers) or ?clump.markers and press return/enter. To see this document from within R you type vignette(`cgmisc`).
\subsection{Purpose of this document}
\noindent This document aims at presenting how to use functions provided in this package in a typical GWAS data analyses workflow. It is, however, not pretending to be a GWAS tutorial as such.
\subsection{Conventions}
\begin{itemize}
\item{All R commands are written in terminal type: myfun(foo=T, bar=54)}
\item{In the above example: \textit{myfun} is a function and both \textit{foo} and \textit{bar} are its arguments}
\end{itemize}

\section*{Working with \texttt{cgmisc}}
\subsection{Installation}
\noindent In order to install \texttt{cgmisc}, you either use one of the R GUIs (native R GUI, RStudio etc.) or type the following command:

<<installing.packages, eval=FALSE, tidy=FALSE, echo=TRUE>>=
 install.packages("cgmisc", repos="")
@

\noindent Functions in the \texttt{cgmisc} package often complement or use \texttt{GenABEL} package functions and data structures.\texttt{GenABEL} is an excellent and widely-used R package for performing genome-wide association studies and much more... Therefore \texttt{GenABEL} will be loaded automagically when loading cgmisc. You can load \texttt{cgmisc} package by as follows:

<<loading.packages, eval=TRUE, tidy=TRUE>>=
  require("cgmisc") 
@

\noindent After having loaded the package it is time to load some data:

<<loading.data, eval=TRUE, results='hide', tidy=FALSE, echo=TRUE>>=
  #setwd("~/Dropbox/cgmisc-devel/cgmisc_jagoda-devel")
  load('data/data.Rd')
@

\subsection{Association Analysis}
\noindent Some of \texttt{cgmisc} functions use data which are the result of GWAS analyses. Let's perform GWAS on our data to obtain \texttt{GenABEL} \texttt{scan.gwaa-class} object : 

<<gwas, eval = TRUE, tidy=TRUE, echo=TRUE>>=
  an0  <- qtscore(response~sex, data = data )
@

\noindent And have a look at top 5 markers

<<summary, echo=TRUE, eval=TRUE>>=
  summary(an0, top = 5)
@


<<setwd, eval=TRUE, results='hide', echo=FALSE>>=
  setwd("~/Dropbox/cgmisc-devel/cgmisc_jagoda-devel/R")
@

\noindent Once this is done, we can proceed with \texttt{cgmisc} functions.

\newpage

\section*{Functions}
\subsection{Plot.Manhattan.LD}
\noindent The \texttt{plot.Manhattan.LD} function allows you to visualize the LD pattern in a genome fragment on an enchanced Manhattan plot. You select one marker, typically the one with the strongest association to the analysed trait and all other markers in the region are coloured according to the degree of linkage disequilibrium with this index marker. 

<<plot.Manhattan.LD>>=
plot.manhattan.LD(data, an0, chr=34, region=c(39e6,42e6), 
                  index.snp = 'BICF2P1063345', bonferroni = F)
@

\subsection{Clump.markers}
\noindent \texttt{clump.markers} function implements clumping procedure described in PLINK documentation. Clumping is based on linkage disequilibrium. The function returns list of clumps which can be used for further analyses or plotted using \texttt{plot.clumps} function included in our package.

<<clump.markers >>=
clumps <- clump.markers(data, gwas.result = an0, chr = 6, bp.dist = 250e3, p1 = 0.0001, p2 = 0.01, r2 = 0.5, image=T)
@

\end{document}
