on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    
    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: ubuntu-22.04, r: '4.1.3'}
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
            r-version: ${{matrix.config.r }}

      - name: Install libraries for GenABEL compilation
        run: |
          sudo apt install libcurl4-openssl-dev libxml2-dev
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "BiocManager", "covr", "png", "RSQLite", "DBI"))
          BiocManager::install("rtracklayer")
          BiocManager::install("GenomicRanges")
          install.packages("https://cran.r-project.org/src/contrib/Archive/GenABEL.data/GenABEL.data_1.0.0.tar.gz", type="source", repos=NULL)
          install.packages("https://cran.r-project.org/src/contrib/Archive/GenABEL/GenABEL_1.8-0.tar.gz", type="source", repos=NULL)
          #source("https://install-github.me/mangothecat/visualTest")
          remotes::install_deps(dependencies = 'Imports')
        shell: Rscript {0}     
      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(args='--no-manual', error_on='error', check_dir='check')"
      - name: Test coverage
        if: matrix.config.os == 'ubuntu-22.04' && matrix.config.r == '4.1.3'
        run: |
          Rscript -e 'covr::codecov(token = "${{secrets.CODECOV_TOKEN}}")'
